src/Entity/Accueil.php
<?php

namespace AcMarche\Mercredi\Entity;

use AcMarche\Mercredi\Entity\Security\Traits\UserAddTrait;
use AcMarche\Mercredi\Entity\Traits\EnfantTrait;
use AcMarche\Mercredi\Entity\Traits\IdTrait;
use AcMarche\Mercredi\Entity\Traits\RemarqueTrait;
use AcMarche\Mercredi\Entity\Traits\TuteurTrait;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TimestampableInterface;
use Knp\DoctrineBehaviors\Contract\Entity\UuidableInterface;
use Knp\DoctrineBehaviors\Model\Timestampable\TimestampableTrait;
use Knp\DoctrineBehaviors\Model\Uuidable\UuidableTrait;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Accueil.
 *
 * @ORM\Table("accueil", uniqueConstraints={
 *     @ORM\UniqueConstraint(columns={"date_jour", "enfant_id", "heure"})
 * })
 * @ORM\Entity(repositoryClass="AcMarche\Mercredi\Accueil\Repository\AccueilRepository")
 * @UniqueEntity(fields={"date_jour", "enfant", "heure"}, message="L'enfant est déjà inscrit à cette date")
 */
class Accueil implements TimestampableInterface, UuidableInterface
{
    use TimestampableTrait;
    use IdTrait;
    use UuidableTrait;
    use EnfantTrait;
    use TuteurTrait;
    use RemarqueTrait;
    use UserAddTrait;

    /**
     * @ORM\Column(name="date_jour", type="date")
     * @Assert\Type("datetime")
     */
    private ?DateTimeInterface $date_jour = null;

    /**
     * @ORM\Column(type="smallint")
     */
    private int $duree;

    /**
     * @ORM\Column(type="string", nullable=false, length=50)
     */
    private ?string $heure = null;

    /**
     * @ORM\ManyToOne(targetEntity="AcMarche\Mercredi\Entity\Enfant", inversedBy="accueils")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Enfant $enfant = null;

    /**
     * @ORM\ManyToOne(targetEntity="AcMarche\Mercredi\Entity\Tuteur", inversedBy="accueils")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Tuteur $tuteur = null;

    public function __construct(Tuteur $tuteur, Enfant $enfant)
    {
        $this->enfant = $enfant;
        $this->tuteur = $tuteur;
        $this->duree = 0;
    }

    public function __toString(): string
    {
        return $this->date_jour->format('Y-m-d');
    }

    public function getDateJour(): ?\DateTimeInterface
    {
        return $this->date_jour;
    }

    public function setDateJour(\DateTimeInterface $date_jour): self
    {
        $this->date_jour = $date_jour;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getHeure(): ?string
    {
        return $this->heure;
    }

    public function setHeure(string $heure): self
    {
        $this->heure = $heure;

        return $this;
    }
}

src/Accueil/Form/InscriptionsType.php
<?php

namespace AcMarche\Mercredi\Accueil\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

final class InscriptionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $formBuilder, array $options): void
    {
        /*  $formBuilder->add(
              'accueils',
              CollectionType::class,
              [
                  'entry_type' => AccueilInlineTpe::class,
              ]
          );*/
    }

    public function configureOptions(OptionsResolver $optionsResolver): void
    {
        $optionsResolver->setDefaults(
            [
            ]
        );
    }
}

src/Controller/Admin/AccueilController.php
<?php

namespace AcMarche\Mercredi\Controller\Admin;

use AcMarche\Mercredi\Accueil\Calculator\AccueilCalculatorInterface;
use AcMarche\Mercredi\Accueil\Form\AccueilRetardAdminTpe;
use AcMarche\Mercredi\Accueil\Form\AccueilType;
use AcMarche\Mercredi\Accueil\Form\SearchAccueilByDate;
use AcMarche\Mercredi\Accueil\Handler\AccueilHandler;
use AcMarche\Mercredi\Accueil\Message\AccueilCreated;
use AcMarche\Mercredi\Accueil\Message\AccueilDeleted;
use AcMarche\Mercredi\Accueil\Message\AccueilUpdated;
use AcMarche\Mercredi\Accueil\Repository\AccueilRepository;
use AcMarche\Mercredi\Accueil\Utils\AccueilUtils;
use AcMarche\Mercredi\Contrat\Facture\FactureHandlerInterface;
use AcMarche\Mercredi\Entity\Enfant;
use AcMarche\Mercredi\Entity\Presence\Accueil;
use AcMarche\Mercredi\Entity\Tuteur;
use AcMarche\Mercredi\Facture\FactureInterface;
use AcMarche\Mercredi\Facture\Repository\FacturePresenceRepository;
use AcMarche\Mercredi\Relation\Repository\RelationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route(path: '/accueil')]
#[IsGranted('ROLE_MERCREDI_ADMIN')]
final class AccueilController extends AbstractController
{
    public function __construct(
        private AccueilRepository $accueilRepository,
        private AccueilHandler $accueilHandler,
        private RelationRepository $relationRepository,
        private AccueilCalculatorInterface $accueilCalculator,
        private FactureHandlerInterface $factureHandler,
        private FacturePresenceRepository $facturePresenceRepository,
        private MessageBusInterface $dispatcher,
    ) {}

    #[Route(path: '/index', name: 'mercredi_admin_accueil_index', methods: ['GET', 'POST'])]
    public function index(Request $request): Response
    {
        $accueils = [];
        $grouped = false;
        $date = null;
        $count = 0;
        $heure = '';
        $form = $this->createForm(SearchAccueilByDate::class, []);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $date = $data['date_jour'];
            $heure = $data['heure'];
            $ecole = $data['ecole'];
            $grouped = $data['groupEcole'];
            $accueils = $this->accueilRepository->findByDateHeureAndEcole($date, $heure, $ecole);
            $count = count($accueils);

            if ($grouped) {
                $accueils = AccueilUtils::groupByEcole($accueils);
            }
        }

        $response = new Response(null, $form->isSubmitted() ? Response::HTTP_ACCEPTED : Response::HTTP_OK);

        return $this->render(
            '@AcMarcheMercrediAdmin/accueil/index.html.twig',
            [
                'accueils' => $accueils,
                'form' => $form,
                'search' => $form->isSubmitted(),
                'grouped' => $grouped,
                'dateSelected' => $date,
                'count' => $count,
                'heure' => $heure,
            ],$response
        );
    }

    #[Route(path: '/list/{id}', name: 'mercredi_admin_accueil_show_enfant', methods: ['GET', 'POST'])]
    public function enfant(Enfant $enfant): Response
    {
        $accueils = $this->accueilRepository->findByEnfant($enfant);
        $relations = $this->relationRepository->findByEnfant($enfant);

        return $this->render(
            '@AcMarcheMercrediAdmin/accueil/enfant.html.twig',
            [
                'accueils' => $accueils,
                'relations' => $relations,
                'enfant' => $enfant,
            ],
        );
    }

    #[Route(path: '/new/{tuteur}/{enfant}', name: 'mercredi_admin_accueil_new', methods: ['GET', 'POST'])]
    public function new(Request $request, Tuteur $tuteur, Enfant $enfant): Response
    {
        $accueil = new Accueil($tuteur, $enfant);
        $form = $this->createForm(AccueilType::class, $accueil);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $result = $this->accueilHandler->handleNew($enfant, $accueil);
            $this->dispatcher->dispatch(new AccueilCreated($result->getId()));

            return $this->redirectToRoute('mercredi_admin_accueil_show', [
                'id' => $result->getId(),
            ]);
        }

        return $this->render(
            '@AcMarcheMercrediAdmin/accueil/new.html.twig',
            [
                'enfant' => $enfant,
                'form' => $form,
            ],
        );
    }

    #[Route(path: '/show/{id}', name: 'mercredi_admin_accueil_show', methods: ['GET'])]
    public function show(Accueil $accueil): Response
    {
        $enfant = $accueil->getEnfant();
        $cout = $this->accueilCalculator->calculate($accueil);
        $coutRetard = $this->accueilCalculator->calculateRetard($accueil);
        $facturePresence = $this->facturePresenceRepository->findByAccueil($accueil);

        return $this->render(
            '@AcMarcheMercrediAdmin/accueil/show.html.twig',
            [
                'accueil' => $accueil,
                'cout' => $cout,
                'coutRetard' => $coutRetard,
                'enfant' => $enfant,
                'facturePresence' => $facturePresence,
            ],
        );
    }

    #[Route(path: '/{id}/edit', name: 'mercredi_admin_accueil_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Accueil $accueil): Response
    {
        if ($this->factureHandler->isBilled($accueil->getId(), FactureInterface::OBJECT_ACCUEIL)) {
            $this->addFlash('danger', 'Un accueil déjà facturé ne peut être modifié');

            return $this->redirectToRoute('mercredi_admin_accueil_show', [
                'id' => $accueil->getId(),
            ]);
        }
        $form = $this->createForm(AccueilType::class, $accueil);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->accueilRepository->flush();

            $this->dispatcher->dispatch(new AccueilUpdated($accueil->getId()));

            return $this->redirectToRoute('mercredi_admin_accueil_show', [
                'id' => $accueil->getId(),
            ]);
        }

        return $this->render(
            '@AcMarcheMercrediAdmin/accueil/edit.html.twig',
            [
                'accueil' => $accueil,
                'form' => $form,
            ],
        );
    }

    #[Route(path: '/delete/{id}', name: 'mercredi_admin_accueil_delete', methods: ['POST'])]
    public function delete(Request $request, Accueil $accueil): RedirectResponse
    {
        $enfant = null;
        if ($this->isCsrfTokenValid('delete'.$accueil->getId(), $request->request->get('_token'))) {
            if ($this->factureHandler->isBilled($accueil->getId(), FactureInterface::OBJECT_ACCUEIL)) {
                $this->addFlash('danger', 'Un accueil déjà facturé ne peut être supprimé');

                return $this->redirectToRoute('mercredi_admin_accueil_show', [
                    'id' => $accueil->getId(),
                ]);
            }

            $id = $accueil->getId();
            $enfant = $accueil->getEnfant();
            $this->accueilRepository->remove($accueil);
            $this->accueilRepository->flush();
            $this->dispatcher->dispatch(new AccueilDeleted($id));
        }

        return $this->redirectToRoute('mercredi_admin_enfant_show', [
            'id' => $enfant->getId(),
        ]);
    }

    #[Route(path: '/{id}/retard', name: 'mercredi_admin_accueil_retard', methods: ['GET', 'POST'])]
    #[IsGranted('accueil_show', subject: 'accueil')]
    public function retard(Request $request, Accueil $accueil): Response
    {
        if ($this->factureHandler->isBilled($accueil->getId(), FactureInterface::OBJECT_ACCUEIL)) {
            $this->addFlash('danger', 'Un accueil déjà facturé ne peut être modifié');

            return $this->redirectToRoute('mercredi_admin_accueil_show', [
                'id' => $accueil->getId(),
            ]);
        }
        $args = [
            'heure_retard' => $accueil->getHeureRetard(),
        ];
        $enfant = $accueil->getEnfant();

        $form = $this->createForm(AccueilRetardAdminTpe::class, $args);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $heureRetard = $data['heure_retard'];
            $delete = $data['delete'];
            if ($delete) {
                $accueil->setHeureRetard(null);
                $this->addFlash('success', 'Le retard a bien été supprimé');
            } else {
                $dateRetard = $accueil->getDateJour();
                $dateRetard->setTime($heureRetard->format('H'), $heureRetard->format('i'));
                $accueil->setHeureRetard($dateRetard);
                $this->addFlash('success', 'Le retard a bien été ajouté');
            }
            $this->accueilRepository->flush();

            return $this->redirectToRoute('mercredi_admin_accueil_show', [
                'id' => $accueil->getId(),
            ]);
        }

        return $this->render(
            '@AcMarcheMercrediAdmin/accueil/retard.html.twig',
            [
                'enfant' => $enfant,
                'form' => $form,
            ],
        );
    }
}

src/Controller/Admin/EcoleController.php
<?php

namespace AcMarche\Mercredi\Controller\Admin;

use AcMarche\Mercredi\Ecole\Form\EcoleType;
use AcMarche\Mercredi\Ecole\Message\EcoleCreated;
use AcMarche\Mercredi\Ecole\Message\EcoleDeleted;
use AcMarche\Mercredi\Ecole\Message\EcoleUpdated;
use AcMarche\Mercredi\Ecole\Repository\EcoleRepository;
use AcMarche\Mercredi\Enfant\Repository\EnfantRepository;
use AcMarche\Mercredi\Entity\Scolaire\Ecole;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Attribute\Route;

#[Route(path: '/ecole')]
#[IsGranted('ROLE_MERCREDI_ADMIN')]
final class EcoleController extends AbstractController
{
    public function __construct(
        private EcoleRepository $ecoleRepository,
        private EnfantRepository $enfantRepository,
        private MessageBusInterface $dispatcher,
    ) {}

    #[Route(path: '/', name: 'mercredi_admin_ecole_index', methods: ['GET'])]
    public function index(): Response
    {
        return $this->render(
            '@AcMarcheMercrediAdmin/ecole/index.html.twig',
            [
                'ecoles' => $this->ecoleRepository->findAllOrderByNom(),
            ],
        );
    }

    #[Route(path: '/new', name: 'mercredi_admin_ecole_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $ecole = new Ecole();
        $form = $this->createForm(EcoleType::class, $ecole);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->ecoleRepository->persist($ecole);
            $this->ecoleRepository->flush();

            $this->dispatcher->dispatch(new EcoleCreated($ecole->getId()));

            return $this->redirectToRoute('mercredi_admin_ecole_show', [
                'id' => $ecole->getId(),
            ]);
        }

        return $this->render(
            '@AcMarcheMercrediAdmin/ecole/new.html.twig',
            [
                'ecole' => $ecole,
                'form' => $form,
            ],
        );
    }

    #[Route(path: '/{id}', name: 'mercredi_admin_ecole_show', methods: ['GET'])]
    public function show(Ecole $ecole): Response
    {
        $enfants = $this->enfantRepository->findByEcoles([$ecole]);

        return $this->render(
            '@AcMarcheMercrediAdmin/ecole/show.html.twig',
            [
                'ecole' => $ecole,
                'enfants' => $enfants,
            ],
        );
    }

    #[Route(path: '/{id}/edit', name: 'mercredi_admin_ecole_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Ecole $ecole): Response
    {
        $form = $this->createForm(EcoleType::class, $ecole);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->ecoleRepository->flush();

            $this->dispatcher->dispatch(new EcoleUpdated($ecole->getId()));

            return $this->redirectToRoute('mercredi_admin_ecole_show', [
                'id' => $ecole->getId(),
            ]);
        }

        return $this->render(
            '@AcMarcheMercrediAdmin/ecole/edit.html.twig',
            [
                'ecole' => $ecole,
                'form' => $form,
            ],
        );
    }

    #[Route(path: '/{id}/delete', name: 'mercredi_admin_ecole_delete', methods: ['POST'])]
    public function delete(Request $request, Ecole $ecole): RedirectResponse
    {
        if ($this->isCsrfTokenValid('delete'.$ecole->getId(), $request->request->get('_token'))) {
            if ([] !== $this->enfantRepository->findByEcoles([$ecole])) {
                $this->addFlash('danger', 'L\'école contient des enfants et ne peut être supprimée');

                return $this->redirectToRoute('mercredi_admin_ecole_show', [
                    'id' => $ecole->getId(),
                ]);
            }
            $ecoleId = $ecole->getId();
            $this->ecoleRepository->remove($ecole);
            $this->ecoleRepository->flush();
            $this->dispatcher->dispatch(new EcoleDeleted($ecoleId));
        }

        return $this->redirectToRoute('mercredi_admin_ecole_index');
    }
}

templates/ecole/accueil/_actions.html.twig
<a href="{{ path('mercredi_ecole_accueil_edit', { 'uuid': accueil.uuid }) }}" role="button"
   class="btn btn-primary"><i
            class="far fa-edit"></i> Modifier</a>

<a href="{{ path('mercredi_ecole_enfant_show', {'uuid': enfant.uuid}) }}" class="btn btn-primary" role='button'><i class="fas fa-list"></i>
    Retour à l'enfant</a>

<br/><br/>

templates/ecole/accueil/_delete_form.html.twig
<!-- Modal candidat -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Supprimer</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">

                </button>
            </div>
            <div class="modal-body">
                Supprimer {{ accueil }} ?
            </div>
            <div class="modal-footer">
                <form method="post" action="{{ path('mercredi_ecole_accueil_delete', {'id': accueil.id}) }}">

                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ accueil.id) }}">
                    <button type="button" class="btn btn-secondary"
                            data-bs-dismiss="modal">Annuler
                    </button>
                    <button type="submit" class="btn btn-danger">Supprimer l' accueil</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/ecole/accueil/_form.html.twig
{{ form_start(form) }}
{{ form_errors(form) }}
<div class="row">
    <div class="col-6">
        {{ form_row(form.date_jour) }}
    </div>
    <div class="col-6">
        {{ form_row(form.duree) }}
    </div>
    <div class="col-4">
        {{ form_row(form.heure) }}
    </div>
    <div class="col-4">
        {{ form_row(form.remarque) }}
    </div>
    {% if form.tuteur is defined %}
        <div class="col-12">
            {{ form_row(form.tuteur) }}
        </div>
    {% endif %}
</div>
<button class="btn btn-primary mr-1 mb-2" type="submit"><i class="far fa-save" aria-hidden="true"></i>
    Sauvegarder
</button>
{{ form_end(form) }}

templates/ecole/accueil/_line_day_inscription.html.twig
<tr>
    <td>
        {{ enfant }}
        <br>
        <span class="text-muted">({{ enfant.anneeScolaire }})</span>
    </td>
    <td>
        {% set tuteurSelected = data[enfant.id]['tuteurSelected'] %}
        {% if enfant.relations|length > 1 %}
            <select name="tuteurs[{{ enfant.id }}][]" class="form-select" required="required">
                <option value="0" {% if tuteurSelected ==0 %}selected="selected" {% endif %}>
                    Sous la garde de
                </option>
                {% for relation in enfant.relations %}
                    <option value="{{ relation.tuteur.id }}"{% if tuteurSelected == relation.tuteur.id %} selected="selected" {% endif %}>
                        {{ relation.tuteur }}
                    </option>
                {% endfor %}
            </select>
        {% else %}
            <input type="hidden" name="tuteurs[{{ enfant.id }}][]"
                   value="{{ enfant.relations[0].tuteur.id }}">
        {% endif %}
    </td>
    {% for day in week.days %}
        {% if day|date('N') < 6 %}
            {% set dateFormate =  day|date('Y-m-d') %}
            {% set accueilData = false %}
            {% if data[enfant.id]['accueils'][dateFormate] is defined %}
                {% set accueilData = data[enfant.id]['accueils'][dateFormate] %}
                {% set value = accueilData.duree %}
            {% else %}
                {% set value = 0 %}
            {% endif %}
            <td>
                <div class="row" {{ stimulus_controller('btns', {
                    updateUrl: path('mercredi_ecole_ajax_duree'),
                    heure: heure,
                    enfant: enfant.id,
                    date: dateFormate
                }) }} >
                    <div class="col mt-sm-1 text-center">
                        <span class="text-muted text-center">{{ day|date('D')|trans }}</span>
                        <br/>
                        <label for="accueilsaccueils[{{ enfant.id }}][]">
                            <input type="number" min="0" max="6"
                                   name="accueils[{{ enfant.id }}][{{ dateFormate }}]"
                                   value="{{ value }}"
                                   data-btns-target="duree"
                                   class="form-control" style="width: 70px;">
                        </label>
                    </div>
                    <div class="col mt-1">
                        <div class="d-sm-flex d-xl-block justify-content-between ">
                            <button type="button"
                                    data-action="btns#up"
                                    class="btn btn-sm btn-outline-primary">
                                <i class="fas fa-plus-square"></i>
                            </button>
                            <button type="button"
                                    data-action="btns#down"
                                    class="btn btn-sm btn-outline-primary">
                                <i class="fas fa-minus-square"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </td>
        {% endif %}
    {% endfor %}
</tr>

templates/ecole/accueil/edit.html.twig
{% extends '@AcMarcheMercrediEcole/layout.html.twig' %}

{% block body %}

    <div class="card mb-3">
        <div class="card-header">
            <h3>{{ accueil.dateJour | format_date('full') }}</h3>
        </div>
        <div class="card-body">

            {{ include('@AcMarcheMercrediEcole/accueil/_form.html.twig') }}

        </div>
        <div class="card-footer">
            <a href="{{ path('mercredi_ecole_accueil_show',{'uuid':accueil.uuid}) }}" class="mt-4">
                <i class="fas fa-long-arrow-alt-left"></i> Annuler
            </a>
        </div>
    </div>

{% endblock %}

templates/ecole/accueil/index.html.twig
{% extends '@AcMarcheMercrediEcole/layout.html.twig' %}

{% block body %}
    <div class="card mb-3">
        <div class="card-header">
            <h3>{% if search %} {{ accueils|length }} {% endif %} Accueils par date</h3>
        </div>
        <div class="card-body">
            {{ form_start(form) }}
            {{ form_errors(form) }}
            <div class="row">
                <div class="col-6">
                    {{ form_row(form.date_jour) }}
                </div>
                <div class="col-4">
                    {{ form_row(form.heure) }}
                </div>
            </div>
            <button class="btn btn-primary mr-1 mb-2" type="submit"><i class="fas fa-search"></i>
                Rechercher
            </button>
            {{ form_end(form) }}

            <table class="table table-bordered">
                <thead>
                <tr>
                    <td>Enfant</td>
                    <td>Date</td>
                    <td>Heure</td>
                    <td>Parent</td>
                    <td>Remarque</td>
                </tr>
                </thead>
                <tbody>
                {% for accueil in accueils %}
                    <tr>
                        <td>
                            <a href="{{ path('mercredi_ecole_enfant_show', {'uuid': accueil.enfant.uuid}) }}">
                                {{ accueil.enfant }}
                            </a>
                        </td>
                        <td>{{ accueil.dateJour| format_date('full') }}</td>
                        <td>{{ accueil.heure }}</td>
                        <td>{{ accueil.tuteur }}</td>
                        <td>{{ accueil.remarque }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5">Rien trouvé</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="card-footer">

        </div>
    </div>
{% endblock %}

templates/ecole/accueil/new.html.twig
{% extends '@AcMarcheMercrediEcole/layout.html.twig' %}

{% block body %}
    <div class="card mb-3">
        <div class="card-header">
            <h3>Nouvel accueil pour <a href="{{ path('mercredi_ecole_enfant_show', {'uuid': enfant.uuid}) }}">{{ enfant }}</a></h3>
        </div>
        <div class="card-body">

            {{ include('@AcMarcheMercrediEcole/accueil/_form.html.twig') }}

        </div>
        <div class="card-footer">
            <a href="{{ path('mercredi_ecole_enfant_show', {'uuid': enfant.uuid}) }}">
                <span class="fas fa-list"></span> Annuler
            </a>
        </div>
    </div>
{% endblock %}

templates/ecole/accueil/show.html.twig
{% extends '@AcMarcheMercrediEcole/layout.html.twig' %}

{% block body %}

    <div class="card mb-3">

        <h3 class="card-header">Accueil de {{ enfant }} le {{ accueil.dateJour|format_date('full') }}</h3>

        <div class="card-body">

            {% include '@AcMarcheMercrediEcole/accueil/_actions.html.twig' %}

            <table class="table table-bordered">
                <tr>
                    <th>Sous la garde de</th>
                    <td>
                        {{ accueil.tuteur }}
                    </td>
                </tr>
                <tr>
                    <th>Nombre de demi-heure</th>
                    <td>{{ accueil.duree }}</td>
                </tr>
                <tr>
                    <th>Quand</th>
                    <td>{{ accueil.heure }}</td>
                </tr>
                <tr>
                    <th>Retard</th>
                    <td>{{ accueil.heureRetard ? accueil.heureRetard|format_datetime('none', 'short') : 'Non' }}</td>
                </tr>
            </table>
            {% if accueil.remarque %}
                <p class="text-muted">
                    {{ accueil.remarque | nl2br }}
                </p>
            {% endif %}

        </div>
    </div>

{% endblock %}