src/Entity/Facture/Creance.php
<?php

namespace AcMarche\Mercredi\Entity\Facture;

use AcMarche\Mercredi\Entity\Security\Traits\UserAddTrait;
use AcMarche\Mercredi\Entity\Traits\IdTrait;
use AcMarche\Mercredi\Entity\Traits\NomTrait;
use AcMarche\Mercredi\Entity\Traits\RemarqueTrait;
use AcMarche\Mercredi\Entity\Traits\TuteurTrait;
use AcMarche\Mercredi\Entity\Tuteur;
use AcMarche\Mercredi\Facture\Repository\CreanceRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TimestampableInterface;
use Knp\DoctrineBehaviors\Contract\Entity\UuidableInterface;
use Knp\DoctrineBehaviors\Model\Timestampable\TimestampableTrait;
use Knp\DoctrineBehaviors\Model\Uuidable\UuidableTrait;
use Stringable;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CreanceRepository::class)]
class Creance implements TimestampableInterface, UuidableInterface, Stringable
{
    use IdTrait;
    use NomTrait;
    use TuteurTrait;
    use TimestampableTrait;
    use RemarqueTrait;
    use UuidableTrait;
    use UserAddTrait;

    #[ORM\ManyToOne(targetEntity: Tuteur::class, inversedBy: 'creances')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Tuteur $tuteur = null;

    #[ORM\Column(precision: 6, scale: 2, nullable: false)]
    #[Assert\Range(min: '0.1')]
    private ?float $montant = 0;
    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?DateTimeInterface $dateLe = null;
    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?DateTimeInterface $payeLe = null;

    public function __construct(
        Tuteur $tuteur,
    ) {
        $this->tuteur = $tuteur;
    }

    public function __toString(): string
    {
        return $this->nom;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(string $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDateLe(): ?\DateTimeInterface
    {
        return $this->dateLe;
    }

    public function setDateLe(?\DateTimeInterface $dateLe): self
    {
        $this->dateLe = $dateLe;

        return $this;
    }

    public function getPayeLe(): ?\DateTimeInterface
    {
        return $this->payeLe;
    }

    public function setPayeLe(?\DateTimeInterface $payeLe): self
    {
        $this->payeLe = $payeLe;

        return $this;
    }
}

src/Entity/Facture/FacturePresence.php
<?php

namespace AcMarche\Mercredi\Entity\Facture;

use AcMarche\Mercredi\Entity\Traits\AbsentTrait;
use AcMarche\Mercredi\Entity\Traits\IdTrait;
use AcMarche\Mercredi\Entity\Traits\NomTrait;
use AcMarche\Mercredi\Entity\Traits\OrdreTrait;
use AcMarche\Mercredi\Entity\Traits\PedagogiqueTrait;
use AcMarche\Mercredi\Entity\Traits\PrenomTrait;
use AcMarche\Mercredi\Entity\Traits\ReductionTrait;
use AcMarche\Mercredi\Facture\FactureInterface;
use AcMarche\Mercredi\Facture\Repository\FacturePresenceRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: FacturePresenceRepository::class)]
#[ORM\Table(name: 'facture_presence')]
#[ORM\UniqueConstraint(columns: ['presence_id', 'object_type'])]
#[UniqueEntity(fields: ['presence', 'objectType'], message: 'Présence existante')]
class FacturePresence
{
    use IdTrait;
    use NomTrait;
    use PrenomTrait;
    use FactureTrait;
    use PedagogiqueTrait;
    use OrdreTrait;
    use AbsentTrait;
    use ReductionTrait;

    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $heure = null;
    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $duree = null;
    #[ORM\Column(type: 'date', nullable: false)]
    private ?DateTimeInterface $presenceDate = null;
    #[ORM\Column(precision: 6, scale: 2, nullable: false)]
    private ?float $cout_brut = null;
    #[ORM\Column(precision: 6, scale: 2, nullable: false)]
    private ?float $cout_calculated = null;
    #[ORM\Column(type: 'string', nullable: true)]
    public ?string $ordre_raison = null;

    #[ORM\ManyToOne(targetEntity: Facture::class, inversedBy: 'facturePresences')]
    private FactureInterface $facture;
    #[ORM\Column(type: 'integer', nullable: false)]
    private ?int $presenceId;
    #[ORM\Column(type: 'integer', nullable: true)]
    public ?int $enfantId;
    #[ORM\Column(type: 'string', length: 100, nullable: false)]
    private ?string $objectType;

    public function __construct(FactureInterface $facture, ?int $enfantId, ?int $presenceId, ?string $objectType)
    {
        $this->facture = $facture;
        $this->enfantId = $enfantId;
        $this->presenceId = $presenceId;
        $this->objectType = $objectType;
    }

    public function getPresenceDate(): ?\DateTimeInterface
    {
        return $this->presenceDate;
    }

    public function setPresenceDate(\DateTimeInterface $presenceDate): self
    {
        $this->presenceDate = $presenceDate;

        return $this;
    }

    public function getCoutCalculated(): ?float
    {
        return $this->cout_calculated;
    }

    public function setCoutCalculated(float $cout_calculated): self
    {
        $this->cout_calculated = $cout_calculated;

        return $this;
    }

    public function getCoutBrut(): ?float
    {
        return $this->cout_brut;
    }

    public function setCoutBrut(float $coutBrut): self
    {
        $this->cout_brut = $coutBrut;

        return $this;
    }

    public function getPresenceId(): ?int
    {
        return $this->presenceId;
    }

    public function setPresenceId(int $presenceId): self
    {
        $this->presenceId = $presenceId;

        return $this;
    }

    public function getObjectType(): ?string
    {
        return $this->objectType;
    }

    public function setObjectType(string $objectType): self
    {
        $this->objectType = $objectType;

        return $this;
    }

    public function getHeure(): ?string
    {
        return $this->heure;
    }

    public function setHeure(string $heure): self
    {
        $this->heure = $heure;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(?int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }
}

src/Entity/Facture/FactureTrait.php
<?php

namespace AcMarche\Mercredi\Entity\Facture;

use AcMarche\Mercredi\Facture\FactureInterface;

trait FactureTrait
{
    private FactureInterface $facture;

    public function getFacture(): FactureInterface
    {
        return $this->facture;
    }

    public function setFacture(FactureInterface $facture): void
    {
        $this->facture = $facture;
    }
}

src/Facture/Form/CreanceType.php
<?php

namespace AcMarche\Mercredi\Facture\Form;

use AcMarche\Mercredi\Entity\Facture\Creance;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CreanceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $formBuilder, array $options): void
    {
        $formBuilder
            ->add(
                'nom',
                TextType::class,
                [
                    'label' => 'Intitulé',
                    'required' => true,
                ]
            )
            ->add(
                'montant',
                MoneyType::class,
                [
                    'required' => true,
                    'help' => 'Uniquement les chiffres',
                ]
            )
            ->add(
                'dateLe',
                DateType::class,
                [
                    'label' => 'Date de créance',
                    'widget' => 'single_text',
                    'required' => true,
                    'attr' => [
                        'autocomplete' => 'off',
                    ],
                ]
            )
            ->add(
                'payeLe',
                DateType::class,
                [
                    'label' => 'Date de paiement',
                    'widget' => 'single_text',
                    'required' => false,
                    'attr' => [
                        'autocomplete' => 'off',
                    ],
                ]
            )
            ->add(
                'remarque',
                TextareaType::class,
                [
                    'required' => false,
                    'label' => 'Remarques',
                    'attr' => [
                        'rows' => 5,
                    ],
                ]
            );
    }

    public function configureOptions(OptionsResolver $optionsResolver): void
    {
        $optionsResolver->setDefaults(
            [
                'data_class' => Creance::class,
            ]
        );
    }
}

src/Facture/Form/FactureAttachType.php
<?php

namespace AcMarche\Mercredi\Facture\Form;

use AcMarche\Mercredi\Entity\Facture\Facture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;

final class FactureAttachType extends AbstractType
{
    public function configureOptions(OptionsResolver $optionsResolver): void
    {
        $optionsResolver->setDefaults(
            [
                'data_class' => Facture::class,
            ]
        );
    }
}

src/Facture/Form/FactureComplementType.php
<?php

namespace AcMarche\Mercredi\Facture\Form;

use AcMarche\Mercredi\Entity\Facture\FactureComplement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\PercentType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

final class FactureComplementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $formBuilder, array $options): void
    {
        $formBuilder
            ->add(
                'nom',
                TextType::class,
                [
                    'required' => true,
                    'label' => 'Raison',
                    'help' => 'Expliquez le motif du complément',
                ]
            )
            ->add(
                'pourcentage',
                PercentType::class,
                [
                    'label' => 'Pourcentage',
                    'required' => false,
                    'type' => 'integer',
                    'help' => 'Le pourcentage est appliqué sur le total de la facture',
                ]
            )
            ->add(
                'amount',
                MoneyType::class,
                [
                    'required' => false,
                    'help' => 'Montant fixe, uniquement les chiffres',
                ]
            )
            ->add(
                'dateLe',
                DateType::class,
                [
                    'label' => 'Date',
                    'widget' => 'single_text',
                    'required' => true,
                    'attr' => [
                        'autocomplete' => 'off',
                    ],
                ]
            );
    }

    public function configureOptions(OptionsResolver $optionsResolver): void
    {
        $optionsResolver->setDefaults(
            [
                'data_class' => FactureComplement::class,
            ]
        );
    }
}

src/Facture/Form/FactureCronType.php
<?php

namespace AcMarche\Mercredi\Facture\Form;

use AcMarche\Mercredi\Entity\Facture\FactureCron;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

final class FactureCronType extends AbstractType
{
    public function buildForm(FormBuilderInterface $formBuilder, array $options): void
    {
        $formBuilder
            ->add(
                'done',
                CheckboxType::class,
                [
                    'label' => 'Terminé',
                    'required' => false,
                ]
            );
    }

    public function configureOptions(OptionsResolver $optionsResolver): void
    {
        $optionsResolver->setDefaults(
            [
                'data_class' => FactureCron::class,
            ]
        );
    }
}

src/Facture/Form/FactureDecompteType.php
<?php

namespace AcMarche\Mercredi\Facture\Form;

use AcMarche\Mercredi\Entity\Facture\FactureDecompte;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

final class FactureDecompteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $formBuilder, array $options): void
    {
        $formBuilder
            ->add(
                'payeLe',
                DateType::class,
                [
                    'label' => 'Date de paiement',
                    'widget' => 'single_text',
                    'required' => true,
                    'attr' => [
                        'autocomplete' => 'off',
                    ],
                ]
            )
            ->add(
                'remarque',
                TextType::class,
                [
                    'required' => false,
                    'label' => 'Remarque',
                ]
            )
            ->add(
                'montant',
                MoneyType::class,
                [
                    'required' => true,
                    'help' => 'Montant payé, uniquement les chiffres',
                    'constraints' => [
                        new Assert\GreaterThan([
                            'value' => 0,
                        ])
                    ],
                ]
            );
    }

    public function configureOptions(OptionsResolver $optionsResolver): void
    {
        $optionsResolver->setDefaults(
            [
                'data_class' => FactureDecompte::class,
            ]
        );
    }
}

src/Facture/Form/FactureEditType.php
<?php

namespace AcMarche\Mercredi\Facture\Form;

use AcMarche\Mercredi\Entity\Facture\Facture;
use AcMarche\Mercredi\Form\Type\MonthWidgetType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;

final class FactureEditType extends AbstractType
{
    public function buildForm(FormBuilderInterface $formBuilder, array $options): void
    {
        $formBuilder
            ->add(
                'nom',
                TextType::class,
                [
                    'required' => true,
                ]
            )
            ->add(
                'prenom',
                TextType::class,
                [
                    'required' => true,
                ]
            )
            ->add(
                'rue',
                TextType::class,
                [
                    'required' => false,
                ]
            )
            ->add(
                'code_postal',
                IntegerType::class,
                [
                    'required' => false,
                ]
            )
            ->add(
                'localite',
                TextType::class,
                [
                    'required' => false,
                ]
            )
            ->add(
                'factureLe',
                DateType::class,
                [
                    'label' => 'Date de la facture',
                    'widget' => 'single_text',
                    'required' => true,
                    'attr' => [
                        'autocomplete' => 'off',
                    ],
                ]
            )
            ->add(
                'mois',
                MonthWidgetType::class,
                [
                    'required' => true,
                ]
            )
            ->add(
                'remarque',
                TextareaType::class,
                [
                    'required' => false,
                    'label' => 'Remarques',
                    'attr' => [
                        'rows' => 5,
                    ],
                ]
            )
            ->add(
                'ecoles',
                TextareaType::class,
                [
                    'required' => false,
                    'label' => 'Écoles',
                    'attr' => [
                        'rows' => 5,
                    ],
                    'constraints' => [new Length(max: 250)],
                ]
            );
    }

    public function configureOptions(OptionsResolver $optionsResolver): void
    {
        $optionsResolver->setDefaults(
            [
                'data_class' => Facture::class,
            ]
        );
    }
}

templates/parent/facture/_accueils.html.twig
{% if factureAccueils | length > 0 %}
    <h4 class="text-success">Accueils</h4>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Enfant</th>
            <th>Date</th>
            <th>Coût</th>
        </tr>
        </thead>
        {% for accueil in factureAccueils %}
            <tr>
                <td>{{ accueil.nom }} {{ accueil.prenom }}</td>
                <td>
                    {{ accueil.presenceDate | format_date('full') }}
                </td>
                <td>{{ accueil.coutCalculated }} €</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

templates/parent/facture/_details.html.twig
{% include '@AcMarcheMercrediAdmin/facture/_details.html.twig' %}

templates/parent/facture/_list.html.twig
<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>Numéro</th>
        <th>Facturé le</th>
        <th>Payé le</th>
        <th>Détails</th>
    </tr>
    </thead>
    <tbody>
    {% for facture in factures %}
        <tr>
            <td>
                N° {{ facture.id }}
            </td>
            <td>
                {{ facture.factureLe | format_date('full') | title }}
            </td>
            <td>
                {% if facture.payeLe %}
                    {{ facture.payeLe | format_date('full') | title }}
                {% else %}
                    <span class="text-danger">Non payée</span>
                {% endif %}
            </td>
            <td>
                <a href="{{ path('mercredi_parent_facture_show', {'uuid': facture.uuid}) }}">
                    Détails
                </a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="5">Aucune</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/parent/facture/_plaines.html.twig
{% if facturePlaines | length > 0 %}
    <h4 class="text-success">Plaine</h4>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Enfant</th>
            <th>Date</th>
            <th>Coût</th>
        </tr>
        </thead>
        {% for accueil in facturePlaines %}
            <tr>
                <td>{{ accueil.nom }} {{ accueil.prenom }}</td>
                <td>
                    {{ accueil.presenceDate | format_date('full') }}
                </td>
                <td>{{ accueil.coutCalculated }} €</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

templates/parent/facture/_presences.html.twig
{% if facturePresences | length > 0 %}
    <h4 class="text-success">Présences</h4>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Enfant</th>
            <th>Date</th>
            <th>Coût</th>
        </tr>
        </thead>
        {% for presence in facturePresences %}
            <tr>
                <td>{{ presence.nom }} {{ presence.prenom }}</td>
                <td>
                    {{ presence.presenceDate | format_date('full') }}
                </td>
                <td>{{ presence.coutCalculated }} €</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

templates/parent/facture/index.html.twig
{% extends '@AcMarcheMercrediParent/layout.html.twig' %}

{% block body -%}

    <div class="card mb-3">
        <div class="card-header">
            <h3>Liste de vos factures</h3>
        </div>

        <div class="card-body">

            {% include '@AcMarcheMercrediParent/facture/_list.html.twig' %}

        </div>
    </div>

{% endblock %}

templates/parent/facture/show.html.twig
{% extends '@AcMarcheMercrediParent/layout.html.twig' %}

{% block body -%}

    <div class="card mb-3">
        <div class="card-header">
            <h3>
                Détails de la facture {{ facture.id }}
            </h3>
        </div>
        <div class="card-body">
            {% if facture.payeLe is null %}
            <div class="alert alert-warning">
                Facture non payée
            </div>
            {% endif %}
            <a href="{{ path('mercredi_commun_export_facture_pdf', {'uuid': facture.uuid}) }}"
               class="btn btn-primary mb-3"
               role='button'> <i class="fas fa-file-pdf"></i> Exporter en pdf</a>
            <a href="{{ path('mercredi_parent_facture_index') }}" class="btn btn-primary mb-3"
               role='button'> <i class="fas fa-list"></i> Retour à la liste</a>

            {{ content|raw }}
        </div>
        <div class="card-footer text-muted mt-3">
            Crée le {{ facture.createdAt | format_date('full') }} par {{ facture.userAdd }}. Mis à jour
            le {{ facture.updatedAt | format_date('full') }}
        </div>
    </div>

{% endblock %}